CREATE TABLE [dbo].[User]
(
	[Id] INT IDENTITY, 
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL, 
	[Email] NVARCHAR(380) NOT NULL, 
	[Password] NVARCHAR(255) NOT NULL,
	[Role] NVARCHAR(32) DEFAULT 'User' NOT NULL,
	CONSTRAINT [PK_User] PRIMARY KEY ([Id]),
	CONSTRAINT[UK_User_Email] UNIQUE ([Email])
)
